model:
  embedding_dim: 128
  hidden_dim: 128
  num_layers: 6
  kernel_size: 15
  dropout_rate: 0.2

training:
  batch_size: 1024
  num_epochs: 200
  learning_rate: 0.001
  model_save_path: "/home/biolib/output"