model:
  embedding_dim: 64
  hidden_dim: 128
  num_layers: 2
  kernel_size: 7
  dropout_rate: 0.1

training:
  batch_size: 1024
  num_epochs: 5
  learning_rate: 0.001
  model_save_path: "/home/biolib/output"